apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: default
  namespace: gloo-mesh
spec:
  options:
    federation:
      enabled: false
    serviceIsolation:
      enabled: false
