apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: tracks-rt-1.0.0
  namespace: gloo-mesh-gateways
  labels:
     portal: dev-portal
     api: tracks-1.0
     # uncomment if you want to hide this API from the portal
     portal-visibility: private
spec:
  portalMetadata:
    apiProductId: Catstronauts
    apiVersion: "1.0"
    title: Catstronauts REST API
    description: REST API for Catstronauts to retrieve data for tracks, authors and modules.
    termsOfService: |
      These Terms of Service ("ToS") govern your access to and use of Catstronauts REST API (the "API"), provided by solo.io ("Provider," "we," or "us").
      By using the API, you agree to comply with these ToS. If you do not agree with any of the terms outlined herein, you must refrain from accessing or using the API.
      
      Acceptance of Terms
      1.1. By accessing or using the API, you acknowledge that you have read, understood, and agree to be bound by these ToS.
      1.2. If you are using the API on behalf of an organization, you represent and warrant that you have the authority to bind the organization to these ToS.
      1.3. These ToS may be updated by us from time to time. The revised terms will be effective upon posting on our website or through other communication means. It is your responsibility to review the ToS periodically.

      API Access and Use
      2.1. Subject to your compliance with these ToS, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the API.
      2.2. You may use the API solely for the purposes outlined in the API documentation provided by us.
      2.3. You agree not to use the API in any way that may violate applicable laws, regulations, or third-party rights.
      2.4. You are responsible for obtaining and maintaining any equipment, software, and internet connectivity required to access and use the API.

      ....
    contact: catstronauts-support@solo.io
    license: |
      Catstronauts REST API License

      Version 1.0

      This Catstronauts REST API License ("License") is a legal agreement between you (either an individual or a legal entity) and solo.io ("Provider") for the use of the Catstronauts REST API ("API").

      By accessing or using the API, you agree to be bound by the terms and conditions of this License. If you do not agree to the terms of this License, you may not use the API.

      1. Grant of License

      Subject to the terms and conditions of this License, Provider grants you a non-exclusive, non-transferable, worldwide license to use the API for the purpose of integrating it into your applications, services, or products ("Your Applications").

      2. API Usage

      ....
    # custom_metadata:
    #   pii-sensitive: "true"
    #   api-category: "demo"
  http:
  - name: tracks-api
    labels:
      cors-policy: api
      usagePlans: dev-portal
    matchers:
    - uri:
        prefix: /
    forwardTo:
      pathRewrite: /
      destinations:
      - ref:
          name: tracks-rest-api-1-0
          namespace: tracks
        port:
          number: 5000
        subset:
          version: 1.0.0
        weight: 80
      - ref:
          name: tracks-rest-api-1-0
          namespace: tracks
        port:
          number: 5000
        subset:
          version: 1.0.1
        weight: 20