apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: dev-portal-rt
  namespace: gloo-mesh-gateways
spec:
  hosts:
    - "developer.example.com"
  virtualGateways:
    - name: istio-ingressgateway
      namespace: gloo-mesh-gateways
  defaultDestination:
    port:
      number: 8080
    ref:
      name: gloo-mesh-portal-server
      namespace: gloo-mesh
      cluster: gg-demo-single
  http:
    - forwardTo: {}
      name: authn
      labels:
        oauth: "true" # apply ext auth policy
        route: portal-api
      matchers:
        - uri:
            prefix: /v1/login
        - uri:
            prefix: /v1/logout
        - uri:
            prefix: /v1/me
        - uri:
            prefix: /v1/api-keys
        - headers:
            - name: Cookie
              value: ".*?id_token=.*" # replace id_token with session if using redis in your oidc ext auth config
              regex: true
    - forwardTo: {}
      name: no-auth
      labels:
        route: portal-api
      matchers:
        - uri:
            prefix: /v1/apis
        - uri:
            prefix: /v1/usage-plans