apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: keycloak-rt
  namespace: gloo-mesh-gateways
spec:
  hosts:
  #- keycloak.keycloak.svc.cluster.local
  - keycloak.example.com
  virtualGateways:
  - name: istio-ingressgateway
    namespace: gloo-mesh-gateways
  http:
  - matchers:
    - uri:
        prefix: /
    forwardTo:
      destinations:
        - ref:
            name: keycloak
            namespace: keycloak
            cluster: gg-demo-single
          port:
            number: 80