apiVersion: apimanagement.gloo.solo.io/v2
kind: PortalGroup
metadata:
  name: tracks-group
  namespace: gloo-mesh-addons
spec:
  name: tracks-group
  description: A group that grants access to the tracks API and allows users in this group to manage API keys for the bronze, silver, and gold usage plans.
  membership:
    - claims:
        - key: group
          value: users
  accessLevel:
    apis:
    - labels:
          api: tracks-1.0
    - labels:
          api: tracks-1.1
    usagePlans:
    - bronze
    - silver
    - gold