apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: api-key-auth-drl
  namespace: default
spec:
  applyToRoutes:
  - route:
      labels:
        usagePlans: dev-portal
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh
      cluster: gg-demo-single
    glooAuth:
      configs:
        - apiKeyAuth:
            headerName: api-key
            headersFromMetadataEntry:
              x-solo-plan: 
                name: usagePlan
                required: true
        - name: opa_auth
          opaAuth:
            modules:
            - name: dynamic-rate-limiting-opa-cm
              namespace: default
            query: "data.test.result"
        # - apiKeyAuth:
        #     headerName: api-key
        #     headersFromMetadataEntry:
        #       x-solo-plan: 
        #         name: usagePlan
        #         required: true
#            k8sSecretApikeyStorage:
#              labelSelector:
#                extauth: apikey
