apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: oauth-api-auth
  namespace: default
spec:
  applyToRoutes:
  - route:
      labels:
        usagePlans: dev-portal
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh
      cluster: gg-demo-single
    glooAuth:
      configs:
        - oauth2:
            accessTokenValidation:
              jwt:
                # localJwks:
                #   inlineString: >-
                #     $KEYCLOAK_CERT_KEYS
                remoteJwks:
                    url: http://keycloak.keycloak.svc.cluster.local/realms/master/protocol/openid-connect/certs
              dynamicMetadataFromClaims:
                usagePlan: usagePlan
        # - opaAuth:
        #     modules:
        #     - name: introspection-policy
        #       namespace: default
        #     query: "data.test.allow == true"