apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: oidc-auth
  namespace: gloo-mesh
spec:
  applyToRoutes:
    - route:
        labels:
          oauth: "true"
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh-addons
      cluster: gg-demo-single
    glooAuth:
      configs:
        - oauth2:
            oidcAuthorizationCode:
              appUrl: http://developer.example.com
              callbackPath: /portal-server/v1/login
              clientId: portal-client
              clientSecretRef:
                name: oauth
                namespace: gloo-mesh-addons
              issuerUrl: http://a89395a557605498bad97c46b31e0c12-191503799.us-east-1.elb.amazonaws.com:8080/auth/realms/master/
              logoutPath: /portal-server/v1/logout
              scopes:
                - email
              # you can change the session config to use redis if you want
              session:
                failOnFetchFailure: true
                cookie:
                  allowRefreshing: true
                cookieOptions:
                  notSecure: true
                  maxAge: 3600
              headers:
                idTokenHeader: id_token