apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerSettings
metadata:
  name: rl-server
  namespace: gloo-mesh
spec:
  destinationServer:
    port:
      name: grpc
    ref:
      cluster: gg-demo-single
      name: rate-limiter
      namespace: gloo-mesh