apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: petstore-rt
  namespace: gloo-mesh-gateways
  labels:
     portal: dev-portal
     api: petstore
spec:
  portalMetadata:
    title: Petstore REST API
    description: Totally awesome API for all things pets!
  http:
  - name: pets-api
    matchers:
    - uri:
        prefix: /pet
    forwardTo:
      pathRewrite: /pet
      destinations:
      - ref:
          name: pets-rest-api
          namespace: default
        port:
          number: 5000
  # - name: users-api
  #   matchers:
  #   - uri:
  #       prefix: /user
  #   forwardTo:
  #     destinations:
  #     - ref:
  #         name: users-rest-api
  #         namespace: default
  #       port:
  #         number: 5000
  # - name: store-api
  #   matchers:
  #   - uri:
  #       prefix: /store
  #   forwardTo:
  #     destinations:
  #     - ref:
  #         name: store-rest-api
  #         namespace: default
  #       port:
  #         number: 5000