apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: tracks-rest-api-1-1-vd
  namespace: tracks
spec:
  hosts:
  # Arbitrary, internal-only hostname assigned to the endpoint
  - tracks-rest-api-1-1-vd.internal.com
  ports:
  - number: 5000
    protocol: HTTP
    targetPort:
      number: 5000
  services:
    - labels:
        app: "tracks-rest-api-1.1"