apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: gateways
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: gg-demo-single
    namespaces:
    - name: gloo-mesh
    - name: gloo-mesh-gateways
    - name: gloo-mesh-addons
  # - name: cluster2
  #   namespaces:
  #   - name: istio-gateways - name: gloo-mesh-addons

