apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: tracks
  namespace: gloo-mesh
  labels:
    allow_ingress: "true" 
spec:
  workloadClusters:
  - name: gg-demo-single
    namespaces:
    - name: tracks
  # - name: cluster2
  #   namespaces:
  #   - name: bookinfo-frontends - name: bookinfo-backends