apiVersion: v1
data:
  config.yaml: aG9zdDogcmVkaXMuZ2xvby1tZXNoLWFkZG9uczo2Mzc5Cg==
kind: Secret
metadata:
  labels:
    app: gloo-mesh-portal-server
    gloo-mesh: gloo-mesh-portal
  name: portal-storage-config
  namespace: gloo-mesh
type: Opaque
---
apiVersion: v1
data:
  key: eHl6OTg3
kind: Secret
metadata:
  labels:
    app: gloo-mesh-portal-server
    gloo-mesh: gloo-mesh-portal
  name: portal-storage-secret-key
  namespace: gloo-mesh
type: Opaque