apiVersion: apimanagement.gloo.solo.io/v2
kind: ApiSchemaDiscovery
metadata:
  name: tracks-rest-api-1-1-service-schema-discovery
  namespace: tracks
  labels:
    # Test to see if this label is included in created ApiDoc ...
    app: my-cool-app
spec:
  openapi:
    fetchEndpoint:
      url: "https://raw.githubusercontent.com/DuncanDoyle/gp-portal-tracks-api-1.1-schema/main/swagger-1.1.json"
  servedBy:
  - destinationSelector:
      kind: SERVICE
      port:
        number: 5000
      selector:
        cluster: gg-demo-single
        name: tracks-rest-api-1-1
        namespace: tracks
  ######################################
  # By using a VirtualDestination in the destinationSelector, we can use different ApiDocs for the same backing K8S Service by simply creating different
  # multiple virtual destinations for the same service.
  # - destinationSelector:
  #     kind: VIRTUAL_DESTINATION
  #     port:
  #       number: 5000
  #     selector:
  #       cluster: gg-demo-single
  #       name: tracks-rest-api-1-1-vd
  #       namespace: tracks